src/api/manager/resolvers.js, src/api/registry.js, src/api/schema.js, src/components/SingleName/NameDetails.js, src/graphql/queries.js
- Adds `Expiration date` (same formatting as "Registration date"). Colour as red if already expired.
- Make it claimable if owner is empty or it is expired
- http://imaginary-summer.surge.sh/name/makoto.test (Expired)
- http://imaginary-summer.surge.sh/name/makoto2.test (Expiring)
- http://imaginary-summer.surge.sh/name/makoto3.test (Not owned)
- http://imaginary-summer.surge.sh/name/resolver.eth (not `.test`)
=> Display expired time

src/api/manager/resolvers.js, src/components/Error/Errors.js, src/routes/SingleName.js, src/utils/utils.js
I've added sanitisation back in, but only to validate a name. The reason it was blowing up before on a...eth was because `web3.utils.sha3` returns null when giving it an empty string. This is a bug that i'll file with web3, but the really it's not an issue for us if we just validate the name so we can't have empty labels. So i've edited the validation function to check for that as well as running the normal domain name validation.
=> Remove sanitisation 2

src/components/SingleName/NameClaimTestDomain.js
This change changes the style of claim button
Change deployed at http://imaginary-summer.surge.sh
=> Make claim button skinny

src/api/registrar.js, src/api/registrar/resolvers.js, src/components/SingleName/NameDetails.js, src/components/SingleName/TransferRegistrars.js, src/graphql/mutations.js, src/testing-utils/deployENS.js
https://www.youtube.com/watch?v=v_UlLSgmm0M
- Show migrate button if the name is registered by old resolver
- Call `transferRegistrars` when migration button is pressed.
- Remove hardcoded registrars addresses (pending on [EIP-1844 work to be updated into `resolver` package](https://discuss.ens.domains/t/ethregistrarcontolloer-address/875))
- Do not show `Migrate` button if the old resolver locking period (28 days) has not passed (pending on  new `ethregistrar ` package to include [this PR](https://github.com/ensdomains/ethregistrar/pull/23/files))
- Incorporate with new design
- "release" button after migration period ends
=> Add transfer registrar

src/api/ens.js, src/api/registrar.js, src/constants/interfaces.json, src/testing-utils/deployENS.js, src/testing-utils/preTest.mjs
@Arachnid 
I set interface signature of the legacy auction registrar as `transferRegistrars` and the new registrar controller as `register` (no need to register base registrar as it is the owner of `.eth`). Let me know if you prefer to use other names for your public net deployments.
=> Set interface implementer

package.json, src/api/ens.js, yarn.lock
@jefflau I think the reason you had issue was that somehow `build/contracts/Resolver.json` was reverted back to `build/contracts/PublicResolver.json` at some point in your branch. Otherwise it would have been failing on live.
=> Point to Resolver, not PublicResolver

src/api/rootResolver.js, src/api/web3.js, src/components/Forms/Button.js, src/components/SingleName/Name.js, src/components/SingleName/NameRegister/CTA.js, src/components/SingleName/NameRegister/NameRegister.js, src/graphql/queries.js
Closes #208 
This is ticket is actually incorrect as the default readOnly env was mainnet, which does not have the permanent registrar up yet. When connecting to ropsten, it will actually display the register button however it fails because there is no wallet available. Therefore this PR is to disable the register button and add a tooltip informing the user they are not connected to a web3 browser
=> Disable register button on readOnly

package.json, src/components/SingleName/NameRegister/notification.js, src/index.js, yarn.lock
https://caniuse.com/#search=notification
on the iOS device, the Global Object `Notification` is unavailable yet.
so we need to add a polyfill to resolve this problem.
=> add notification polyfill for ios safari

src/api/web3.js
Currently, some provider doesn't support `subscription` but has `on` method (for the EIP1193 eventEmitter).
in web3.js 1.0.0-beta.34, if the provider has `on` method, it will not fallback to receipt polling.
it just sends `eth_subscribe` RPC request, so if the provider or node doesn't support `subscription`, the `.on('receipt'` will never get fired.
in the latest version of web3.js, the judge condition is changed to:
Right now, we only can avoid the condition check by resetting the `on` method of the provider.
while Metamask doesn't have this problem, cause they don't send `eth_subscribe` request to node server, the polling every block, and fire the event by themselves.
This is a temporary solution, we will fix it in the future.
=> fix: some provider not support eth_subscrbe

src/routes/SingleName.js
Looks like I broke this when I (or was it Jeff? I can't remember) refactored to normalise the name so if people go something  like http://manager.ens.domains/name/aaaa it was showing blank page rather than displaying `Domain tld unsupported. aaaa is not currently a support tld.`
=> Set type to unsupported

package.json, src/routes/SearchResults.js, src/utils/utils.js, yarn.lock
This is to partly fix [this](https://github.com/ensdomains/ens-app/issues/282)
- Searching 👩‍❤️‍👨👩‍❤️‍👨displays unnormalised format (👩‍❤️‍👨👩‍❤️‍👨)
- `/search/👩‍❤️‍👨1` was allowed as it was counted as 7 (6 char + 1)
- `/name/👩‍❤️‍👨1.eth` was showing `unsupported tld` error.
- It should reformat to normalised version (👩‍❤‍👨👩‍❤‍👨)
- `/search/👩‍❤️‍👨1` and `/name/👩‍❤️‍👨1.eth` should show `name too short` but `/search/👩‍❤️‍👨12` and `/search/👩‍❤️‍👨12.eth` should be ok.
- Replace `uts46` with `normalise` function of `ethereum-ens` per [Nick's suggestion](https://github.com/ensdomains/ens-app/issues/282#issuecomment-492809999)
Redirect to normalised URL
=> Show parsed search result

package.json, src/routes/SearchResults.js, src/routes/SingleName.js, src/utils/utils.js, yarn.lock
* Fixes #282 (no redirection yet)
* Check length against normalised unicode
* Replace uts46 with eth-ens-namehash
* Fix problem of displaying 'Domain tld unsupported. eth is not currently a support tld.' for a short name
=> Show parsed search result (#324)

src/apolloClient.js, src/components/hooks.js, src/index.js
Hi there!
Whenever I try to reach ens-app over Opera Browser, If Metamask enabled, I'm having this issue;
```js
Uncaught (in promise) TypeError: Cannot read property 'mutate' of undefined
at index.js:20
at u (runtime.js:45)
at Generator._invoke (runtime.js:264)
at Generator.e.<computed> [as throw] (runtime.js:98)
at r (asyncToGenerator.js:3)
at f (asyncToGenerator.js:29)
```
Opera version: 63.0.3368.75
After solving the issue above, if I search an ens name which already owned by someone else, I see this error;
```
Unhandled Rejection (TypeError): Cannot read property 'ethusd' of undefined
```
So, the PR intended to fix them.
=> Fix: Cannot read property 'mutate' of undefined in Opera Browser

.travis.yml
`yarn` kept failing when installing sha3 (which I am not sure where the dependency is coming from).
After the google research I bumped into the github issue which suggest to downgrade.
https://github.com/phusion/node-sha3/issues/32#issuecomment-385259045
=> Downgrade node to 8.11 on Travis

.travis.yml
It was complaining that some cypress dependency had an incompatible versions. As a solution, specify the exact cypress version into Travis as same as the one specified at package.json
=> Install the same version of cypress

cypress/integration/resolverMigration.spec.js, package.json, src/api/ens.js, src/api/manager/resolvers.js, src/api/registrar/resolvers.js, src/api/rootResolver.js, src/api/subDomainRegistrar/resolvers.js, src/index.js, src/utils/utils.js, yarn.lock
Add in new UI library that allows instantiating new registries
=> Update to new ENS class

.travis.yml
This is to fix `error stellar-base@2.1.3: The engine "node" is incompatible with this module. Expected version ">=10.16.3"` error
=> Upgrade node.js to lts/dubnium

.travis.yml, cypress.json, cypress/integration/address.spec.js, cypress/integration/nameDetail.spec.js, cypress/integration/resolverMigration.spec.js, cypress/integration/subgraph.spec.js, package.json, src/index.js, src/testing-utils/preTest.js, yarn.lock
* Update travis.yml
* Simplify cypress:ci command
* Go to correct dir
* Remove preTest from cypress:ci as it runs at before_script
* hardcode labelhash
* Add test to check graph api is up and running
* Revert testing.eth
* Change assertion
* Increase timeout
* Revert test logic
* Add test labels
* Add cd
* Disable storing test labels
* Add labels from mock file
* Use sub1 label for testing
* Add spec to test address
* Add wait time
* Change to single quote
Co-authored-by: Makoto Inoue <makoto@Makotos-iMac.lan>
=> Deploy to live

src/components/Links/ContentHashLink.js
Potentially solves #623 
As mentioned in the comment in the issue, many .onion sites do not have SSL certs, and some even see them as detrimental. I have yet to see a v3 (super long 56 character addresses) address that can be accessed using `https://`, including the [CIA](ciadotgov4sjwlzihbbgxnqg3xiyrg7so2r2o3lt5wz5ypk4sxyjstad.onion)'s, though I cannot confirm if there's something built in to these addresses that doesn't allow it.
As a result of the above, this PR proposes connecting to .onion content using `http://`, not `https://`. Since .onion sites are already end-to-end encrypted, this shouldn't weaken security. (Some sources linked in #623 in the comment.)
=> use http for .onion content

src/components/Address/Address.js, src/components/Links/EtherScanLink.js
Fixes and improvements for Etherscan link of user address.
Resolves #692 .
Etherscan address was passed wrong in `Address` component, with fix works as intended.
Manual Testing
=> Fix etherscan link

public/locales/de.json, public/locales/en.json, public/locales/ja.json
* Modified short domain error copy from "must be 7 characters" to "must be 3 characters" since https://medium.com/the-ethereum-name-service/the-most-popular-eth-names-in-the-ens-short-name-auction-final-5d3466dd8837 "Next Steps" paragraph (https://twitter.com/ensdomains/status/1192169148815728640)
-
-
-
=> Changed copy from 7 character min to 3 character min

public/locales/de.json, public/locales/en.json, public/locales/ja.json
In the Manager copy changed, "premium" had a typo, and the word "date" didn't really make sense by itself. I've adjusted it to make more sense.
=> Typo correction

src/components/Address/Address.js, src/utils/utils.js
https://github.com/ensdomains/ens-app/issues/931
-  shows `addr.reverse` as part of the the controller the address own.
- can go to `name/***.addr.reverse`
- `name/addre.reverse/subdomains` shows the list of reverse records
=> Display reverse records

package.json, src/api/registrar/resolvers.js, src/components/SingleName/NameRegister/NameRegister.js, src/components/SingleName/NameRegister/ProgressRecorder.js, src/graphql/queries.js, yarn.lock
This will check if commitment exists based on label x secret and if it does exists set as blockCreatedAt.
This change should allow user to continue the process even when their step 1 transaction failed or they increased the gas price (user still has to refresh the page though).
=> Check commitment

src/components/Header/Header.js, src/components/LanguageSwitcher/LanguageSwitcher.js
Language overlay seems broken since I integrated wallet modal 
This PR is to fix the issue
=> Fix language dropdown display bug

src/components/Forms/Select.js, src/components/SingleName/ResolverAndRecords/AddRecord.js
Improve the usability and accessibility of the selector components by:
- Sorting options for easier scrolling
- Increase the contrast of non selected options for better visibility
None.
The `Select` component is currently showing non selected items in the same contrast as disabled items, which impacts its accessibility.
The `AddRecord` component is creating selectors from list of items that seems to be in a random order which makes scrolling harder since there is no way to tell where an item might be in a very long list.
- Selector: Increased visibility of non selected options
- AddRecord: Sorted coin selector options
- AddRecord: Sorted text record type selector options
Change was tested by running the app locally with `yarn start`, the app was working as expected.
Unfortunately I was …
=> Sort options selectors to improve usability and accessibility

src/components/AddReverseRecord.js, src/components/Forms/Select.js
1. Make "Reverse record not set" more visible when the user can edit it.
2. Make text record lowercase as default to solve https://github.com/ensdomains/ens-app/issues/1091
=> Minor changes

public/locales/cn.json, public/locales/de.json, public/locales/en.json, public/locales/es.json, public/locales/fr.json, public/locales/ja.json, public/locales/ko.json, public/locales/pl.json, public/locales/ru.json, public/locales/vi.json, src/api/manager/resolvers.js, src/components/SingleName/NameDetails.js, src/routes/Faq.js
Resolve https://github.com/ensdomains/ens-app/issues/1104
It shows the following warning if 2ld is empty and owner is not dnsregistrar
=> Override registrar address only if tldowner is empty

src/api/labels.js, src/components/AddReverseRecord.js
http://localhost:3000/address/0xcf88FA6eE6D111b04bE9b06ef6fAD6bD6691B88c is throwing error because some domain does not have name on subgraph
=> do not throw when domain has no name

src/api/manager/resolvers.js, src/components/NetworkInformation/NetworkInformation.js
- Do not show reverse name if it does not have a forward record or fails on normalisation
- Couldn't write the test as I couldn't make cypress up and running on my local machine
=> Check forward record

src/components/SearchName/Search.js
https://github.com/ensdomains/ens-app/issues/1152
Whitespace wasn't being trimmed as mentioned in the issue, so I split the search by into an array, then map() to trim each array item, and lastly join() back into a string
- Validates user input
I searched some of the following terms to see if the 'malformed error' showed up:
" foo.eth", "foo .eth", "foo. bar.eth "
Gif of new search
- [ x] My code follows the code style of this project.
- [ x] My code implements all the required features.
=> handleParse() trims all whitespace in Search component

src/components/Calendar/Calendar.js, src/components/ExpiryNotification/ExpiryNotifyDropdown.js, src/components/LanguageSwitcher/LanguageSwitcher.js, src/components/hooks.js
Improvement on top of #1190 for #1161. 
This PR aims to exclude toggler of dropdown items from clicking outside effect. Without this PR, if user opens a dropdown and click to the toggler for closing purpose, it will close the dropdown just because user clicked outside of the dropdown, but later it will be reopened because in fact user clicked on toggler (button/link/icon etc).
=> Exclude dropdown toggler from click outside effect

package.json, src/components/hooks.js, yarn.lock
Gas price estimation will now be based on the previous block's base fee when we are able to send EIP-1559 transactions. Otherwise we will default to the old method for estimating gas. 
Also ganache doesn not support the london hard fork so unable to run cypress tests for 1559 transactions at the moment.
Tested manually on ropsten
=> Gas price estimation fix

src/components/SingleName/DNSNameRegister/CTA.js
Initially, it was throwing `uncaught invariant violation` error when registering `black.host` and `goose.glass`
=> Use @apollo/client/react/component on mutation

src/components/SingleName/DetailsItemEditable.js, src/components/SingleName/NameRegister/CTA.js, src/components/SingleName/NameRegister/Premium.js
#1168 
When creating a google reminder, the startDatetime passed as a query param to Google calendar is in UTC time (uses moment.utc()) instead of local time.
This results in a startDatetime with a utc offset of +0:00:
When switching from UTC to local time using moment.local() method, this results in a startDatetime with a UTC offset that is the same as the local computer:
- startDateTime prop passed to AddToCalendar component in name page
When running chromium with different TZ environment variable / timezones, it displays a startDateTime with the timezone corresponding UTC offset instead of a UTC offset of +0:00.
=> Switch to local time (#1168)

src/components/AddReverseRecord.js, src/components/DomainItem/ChildDomainItem.js
#1186
#1179
The transaction pending message should only disappear once the transaction is complete.
Address page 
When the transaction to set the reverse ENS record is approved in the wallet service, the pending message remains now visible and the reverse record editor is disabled until the transaction is executed.
Name page (subdomain)
The tx pending message is nested in the anchor tag and when trying to delete the subdomain, the tx pending message is clickable. This PR only displays the tx pending message when clicking on the bin until the transaction is executed.
- Do not trigger `startEditing` handler function on click event as long as tx is pending 
- Set cursor to default on hovering in the `ReverseRecordEditor` when tx pending 
- Do not show pending msg when tx signature is denied …
=> Fix UI pending transaction

src/components/SingleName/DNSNameRegister/DNSNameRegister.js
I had a crash occur on the app.ens.domains site when attempting to use a DNS record as an ENS name. I'm not quite sure where the actual error is, but this surfaced as `TypeError: Cannot read properties of undefined (reading 'toLowerCase')` at this line, it seems `account` can sometimes be undefined.
This error presented itself as blanking the entire screen, so not a great user experience. Any attempts to use the site for my DNS record experiences this error, resulting in a blank screen. So this doesn't really solve the problem, but this should hopefully prevent the entire site from crashing to a blank screen.
I think this relates to #1284
Added a guard so an undefined account doesn't crash the website.
- A guard for if account is undefined.
Nope, I'm making this change blind in Github and …
=> Fixed a crash case when there is no account, unsure why.

.travis.yml
Some builds are failing on preview branch creation. It is not worth fixing now as we will soon get them for free once we move to netlify.
=> Remove preivew branch creation

src/components/SideNav/SideNav.js
Use Info icon instead of SpeechBubble for about page
`SideNav.js`
Before
After
=> feat: use Info icon instead of SpeechBubble for about page

src/components/SingleName/AddSubdomain.js
#1343 
This PR resets the value of the input field to an empty string after confirming the transaction to create a subdomain.
- set `newValue` state to an empty string in the callback function triggered when mutation successfully completes
- Do not show pending msg or reset the state when tx signature is denied (e.g. click "reject" in the Metamask popup)
Run changes against existing unit tests:
=> Set input field to empty string after tx approval

src/components/DomainItem/ChildDomainItem.js, src/components/SingleName/SubDomains.js
#1345
Refetch the subdomains queries in response to a successful subdomain deletion.
- Pass refetch function from Query component as a prop to `SubDomainsFromWeb3` and `SubDomains`
- Call refetch function once subdomain deletion tx is successfully executed 
Run changes against existing unit tests:
N/A
=> Refetch list of subdomains after deletion

src/components/AddReverseRecord.js
A reasonably significant amount of users get confused about if they have a primary name set or not on their address page, which leads some to send a transaction multiple times for doing so. This PR clarifies that confusion.
+ Stop primary name edit box from being opened automatically if the user has one set
+ Set the primary name message colour to be darker if the user has one set
As it's a very small change, it's just been tested in a browser manually. 
| Before (With primary name set, on page load) | After (With primary name set, on page load) |
| ----------- | ----------- |
| ![Screenshot 2021-11-26 161359](https://user-images.githubusercontent.com/11844316/143531090-badd41d1-983a-4e0a-892f-d41e531c8de5.png) | ![image](https://user-images.githubusercontent.com/11844316/143531063-f9803d6 …
=> Add primary name status clarity on address page

src/components/Banner/DAOBanner.js, src/routes/Home.js
#1368
Alternative text is missing on ENS icons and the arrow img on the banner (home page) causing some screen readers to read the value of the `src` attribute aloud. 
- Added an alt attribute to `LogoSmall`, `LogoLarge` and `ArrowSmall` components 
Tested with the Orca screen reader from the GNOME project (version 3.36.2).
Before:
After:
=> Add img alternative text

src/components/SingleName/Name.js
closes https://github.com/ensdomains/ens-app/issues/928
Currently, an expired domain cannot be reregistered by the same owner.
This limitation is because the `isDeedOwner` check makes the
registration availability come back false for the previous registrant.
I'd love to be able to reregister domains I lost track of ;)
This change removes the isDeedOwner check from this logic. There may
unintended consequences of this change and I am not sure
how best to test this change. I am very open to feedback. Thanks!
- An account who previously registered a domain that is currently expired can now reregister the domain again.
Locally, I was able to see the registration UI for a domain that was previously registered but now expired.
Before the change:
After the change:
=> Allow previous registrants to reregister expired domains

src/components/SingleName/Pricer.js
fix: center align OrangeExclamation icon and message in prompt
Before
After
=> fix: center align OrangeExclamation icon and message in prompt

src/components/SingleName/NameRegister/Years.js
#1358
When the content of the registration period input is too big to fit in the element, the overflow is clipped. This PR increases the value of the `max-width` property to allow the number of years to go up to 4 digits so that there is no overflow anymore.
I left the content of the `Amount` component left aligned horizontally. I can also center it if you'd prefer.
- `max-width` property increased by `20px`
- content of the input element centered 
- padding adjusted to be symmetrical
Simulated the viewport on different mobile devices and on desktop. Also tested with all the languages currently available in the manager app.
Before:
After:
=> Increase max-width registration period input

package.json, src/utils/safeApps.js, yarn.lock
#1332 
Fixes connection to the Safe interface by using a correct method to retrieve Safe information, adds error logging for the future, and also fixing returns in `setupSafeApp`(it returned network info, but the users of this function expected a provider)
Also, the PR bumps `safe-apps-provider` version
I ran the Safe and ENS App locally, and when I loaded the ENS app, it could connect to the interface and display Safe address.
=> Fix Safe App connection

src/api/avatar.js, src/components/SingleName/ResolverAndRecords/AddRecord.js, src/components/SingleName/ResolverAndRecords/KeyValueRecord/KeyValueRecord.js, src/components/SingleName/ResolverAndRecords/Records.js, src/utils/records.js, src/utils/utils.js
Quite a few users have used a significant amount of gas on setting their avatar record to fields that are either incorrectly formatted, or using NFTs that they don't own/don't have a tokenURI. This PR adds validation to the avatar field with basic checks in place, to ensure a user doesn't accidentally enter incorrect information.
All unit tests passed
=> Add avatar record validation

src/components/SearchName/Search.js
Fixes #1271 
Set autocapitalize="off" on the search field so that it doesn't capitalize
=> Set autoCapitalize="off" on search field

src/components/Links/AddressLink.js, src/components/Links/ContentHashLink.js, src/components/Links/RecordLink.js, src/components/SingleName/DetailsContainer.js, src/components/SingleName/DetailsItemEditable.js, src/components/SingleName/NameRegister/Years.js, src/components/SingleName/ResolverAndRecords/RecordsItem.js
#1368
This PR adds aria labels to anchor and input elements which can be read aloud by a screen reader.
- record's type in the ENS name's content record
- domain's details (parent, registrant, controller, expiration date and resolver)
- registration period input
Tested with the Orca screen reader from the GNOME project (version 3.36.2).
N/A
=> Add aria labels

src/components/SingleName/DetailsItemEditable.js, src/components/SingleName/DetailsItemInput.js, src/components/SingleName/ResolverAndRecords/AddRecord.js, src/components/SingleName/ResolverAndRecords/ContentHash.js, src/components/SingleName/ResolverAndRecords/KeyValueRecord/KeyValueRecord.js, src/utils/records.js
#1382
Upon pasting an address in the Resolver field or a record entry with leading or trailing spaces, it displays a malformed error. This PR trims off any leading or trailing whitespace unless the record type is a description, notice, keywords, name or location.
I have appended and prepended whitespace to the input and then pasted it to see if the malformed warning showed up. All unit tests pass:
N/A
=> Trim whitespace

src/setup.js
#1402 
We need to call setup again if the network changes so that the correct contract addresses can be recalculated
Load the app with goerli initially, change to mainnet, renew a name and check the destination address of the transaction
=> Call setup again if network changes

src/routes/Favourites.js
#1386
After the last domain is deleted form the list of favourites (`favourites` constant is then an empty array), `NoDomains` component is returned and `useAccount` custom hook is therefore no longer invoked which throws an error. Hooks should be called in the same order each time a component renders and not invoked conditionally. This PR moves the `useAccount` hook up to the top level of the Favourites component so that it gets called regardless of whether the list of favourites is empty or not.
No longer throws an error when clicking on the heart icon of the last domain in the list and all existing unit tests pass:
N/A
=> Hooks invoke conditionally in Favourites component

src/components/Calendar/RenewalCalendar.js
=> Fix typo in RenewalCalendar.js

src/routes/Faq.js
- Several contractions used commas `,`. These were replaced with apostrophes `'`.
- One instance of `.eth` was enclosed with mismatching `‘` and `` ` `` characters. These were replaced with quotes to match other instances of `.eth` in the FAQ.
- Added a space: `step3` -> `step 3`.
- Proofread the text several times
n/a
=> Fix FAQ typos

src/components/Banner/DAOBanner.js
Fixes #1413 
By removing the `height: 100%;` from the ArrowSmall styling, the image no longer takes up unnecessary space. 
100% height was not needed for this component.
- Verified that the height of the banner looks good on **Mobile** by using Safari's Responsive Design Mode to emulate different mobile screen sizes.
- Verified that the height of the banner looks the same as before on **Desktop** in Chrome, Safari, Brave, and FireFox.
=> Fix DAO Banner height on mobile

src/components/SingleName/ResolverAndRecords/AddRecord.js
#1408
After setting a record and clicking on the Save button, the button remains clickable. This PR sets the state of `isValid` and `isValidating` to `false` so that the button is disabled.
- `isValid` and `isValidating` states are set to `false` when clicking on save to add a record
Run changes against existing unit tests:
N/A
=> Reset isValid and isValidating on save (#1408)

src/api/labels.js, src/api/labels.test.js, src/components/DomainItem/ChildDomainItem.js
#1400
As per issue, if the preimage / subdomain name is not known, the 0x labelhash shows instead on the subdomains page of the ens manager app. When deleting such subdomain without known preimage, the labelhash is hashed a second time before being included as argument in the `setSubnodeRecord` method of the ENS registry. This PR checks whether the label is a 32 bytes hexadecimal string or not and if yes, the label is encoded (i.e. removes "0x" prefix and wrapped in brackets) so that the labelhash is not hashed a second time in the `labehash` function before sending the transaction to the network.   
Added unit tests for `encodeLabel` and `parseName` functions
N/A
=> Fix subdomain deletion unknown preimage

src/components/SingleName/NameRegister/Years.js
https://github.com/ensdomains/ens-app/issues/1421
Describe the bug
See the reproduce below. I add some screenshots
To Reproduce
Steps to reproduce the behavior:
1. Go to 'https://app.ens.domains/name/aaabbbccc.eth/register', an unregister domain
2. Input a numer greater then 1 year, for example 5 years
3. Click then '+' button right the input, expect '6' , but '51' display.
4. See error
Expected behavior
When people click '+' button, we expect the number N+1, not the string plus 'N1'.
no feature
Tested. online demo see at https://ens-app-ten.vercel.app/name/statexxx.eth/register
when I input '5'
when I clicked the '+' icon
=> fix: unexpected plus behavior on the Registration Period Input

src/components/SingleName/NameRegister/LineGraph.js
- Chang tooltip display position
- Add padding 
NOTE: I have problem automatically changing tooltip position so it may not necessarily show the tooltip well on mobile on top left.
=> Make tooltip visible for exponential premium chart

public/locales/en.json, src/components/SingleName/Name.js, src/components/SingleName/NameDetails.js, src/components/SingleName/NameRegister/CTA.js, src/components/SingleName/NameRegister/NameRegister.js
Before:
- The registration page would show an insufficient balance message if no wallet was connected
- The connect button was not easily seen anywhere on the page on mobile
- "readOnly" was being interchanged between readOnly state for disconnected wallet, and readOnly state for being a wrapped name.
After:
- The registration page shows a message that a wallet needs to be connected
- A connect button is shown as a replacement for the request to register
- "readOnly" was replaced with "isNameWrapped" and "isReadOnly"
Related issue: #1513
=> Fix NameRegister connection status

src/components/SingleName/NameDetails.js, src/components/SingleName/NameDetails.spec.js
This fixes thw two issues
- https://app.ens.domains/name/name/matoken.eth/ (with trailing `/` does not redirect to https://app.ens.domains/name/name/matoken.eth)
- https://app.ens.domains/name/name/argent.xyz and https://app.ens.domains/name/1.offchainexample.eth (subdomains and non .eth domains) redirecting to /subdomains instead of /details
=> Change redirect logic

scripts/serve.js, src/hash/index.js, src/hash/namehash.js
- emoji names are currently broken (see #1504)
- this is because of ensdomains/UI's reliance on ethers Resolvers which use ethers namehash
- ethers namehash function is a different implementation to what is used in the rest of the app
- this PR overwrites that function, allowing emoji names to work
=> fix: emoji names

cypress/integration/nameDetail.spec.js, cypress/integration/nameWrapper.spec.js, cypress/integration/resolverMigration.spec.js, cypress/integration/search.spec.js, public/locales/en.json, src/api/manager/resolvers.js, src/components/SingleName/DetailsItemEditable.js, src/components/SingleName/ResolverAndRecords/ResolverAndRecords.js
- hides resolver field under advanced settings at bottom of page
- gives a warning/info message about the resolver
- unmigrated resolver remains unchanged
=> Improve Resolver UX

src/apollo/apolloClient.js
Catch namehash error in order to allow a list of names to be displayed when some of them are invalid
#1533 
Catch errors in graphql middleware in order to allow invalid names to be displayed with an error
Visited http://localhost:3000/address/0x8ead5a81e5eaab60ee6e24d85b8ed21182a6cc29/registrant?page=1
=> show-invalid-names-with-warning

src/api/web3modal.js, src/setup.js, src/setup.spec.js, src/utils/utils.js
Tested with metamask and wallet connect by landing on the page on an unsupported network as well as switching to an unsupported network while using the app.
=> Prompt user to switch network if they are on an unsupported one
