ensdomains/ens-app

- .travis.yml
- src/components/SearchName/Search.js
just test if travis deploy is working
> addresses 1

- cypress/integration/search.spec.js
- src/components/AddFavourite/AddFavourite.js
- src/components/NetworkInformation/NetworkInformation.js
- src/components/SingleName/AddReverseRecord.js
- src/components/SingleName/SaveCancel.js
- src/routes/Favourites.js
- src/testing-utils/deployENS.js
- Check reverse record is displayed on nabvar
- Check if main page prompts to change reverse record 
- Add/Remove favorites
- Make save with confirmation optional (ignore if `isValid` is `undefined`).
> Reverse record test

- cypress/integration/register.spec.js
- src/api/ens.js
- src/api/manager/resolvers.js
- src/api/registry.js
- src/components/SingleName/Name.js
- src/components/SingleName/NameClaimTestDomain.js
- src/components/SingleName/NameDetails.js
- src/graphql/mutations.js
- src/testing-utils/deployENS.js
If you are connected to Rinkeby or Ropsten and search an `.test` name which is not owned by anyone, you should be able to claim the ownership by pressing "Claim the test domain".
The change is deployed at https://imaginary-summer.surge.sh
> Test registrar

- src/components/Forms/Button.js
- src/components/SingleName/TransferRegistrars.js
https://github.com/ensdomains/ens-app/issues/116
> Style migration button

- src/routes/SingleName.js
This fixes https://github.com/ensdomains/ens-app/issues/128
> Prevent going infinite loop

- package.json
- src/api/__tests__/ens.test.js
- src/api/ens.js
- src/api/registrar.js
- src/api/registry.js
- src/components/Error/Errors.js
- src/components/SingleName/NameDetails.js
- src/routes/SingleName.js
- yarn.lock
Added normalization of name for setSubnodeOwner
Fixed #148
> Normalize names in Single Name page

- src/components/ExternalLinks/ContentHashLink.js
- src/utils/contents.js
Should fix https://github.com/ensdomains/ens-app/issues/115
> Show contenthash decoding error message.

- src/components/SingleName/DetailsItemEditable.js
Testing commit/PRs with macbook air
> Fix warnings

- src/api/manager/resolvers.js
- src/api/registrar.js
- src/api/registrar/resolvers.js
- src/components/SingleName/NameDetails.js
- src/components/SingleName/NameRegister/NameRegister.js
- src/graphql/mutations.js
- src/graphql/queries.js
> Add registrant for .eth names

- src/components/SearchName/DomainInfo.js
- src/routes/SearchResults.js
> Use SingleName query over legacy auction state

- src/components/SingleName/NameRegister/CTA.js
- src/components/SingleName/NameRegister/NameRegister.js
> use parseFloat instead of parseInt

- src/api/registrar.js
- src/api/registry.js
I am guessing that the transaction was failing because it was checking the owner but does not know who the transaction is sending from.
> Fix estimateGas error

- src/components/SingleName/NameDetails.js
- src/routes/SearchResults.js
> Allow owner to set controller

- src/components/SingleName/Confirm.js
- src/components/SingleName/DetailsItemEditable.js
- src/components/SingleName/NameDetails.js
> Change owner to registrant. Transfer/Set terminology.

- src/routes/SingleName.js
This is to fix https://github.com/ensdomains/ens-app/issues/197
> Show error when short name eth address is specified under /name

- src/components/SingleName/DetailsItemEditable.js
- src/components/SingleName/NameDetails.js
> Allow anyone to renew

- package.json
- src/api/registrar.js
- src/api/registrar/resolvers.js
- src/components/NetworkInformation/NetworkInformation.js
- src/components/SingleName/DetailsItemEditable.js
- src/components/SingleName/NameDetails.js
- src/components/SingleName/NameRegister/NameRegister.js
- src/graphql/mutations.js
- src/testing-utils/deployENS.js
- yarn.lock
* Allow anyone to renew
* Disable register button on readOnly. Add tooltip to prompt user to connect to wallet
* Added 'Network' to network name to make it more obvious what network a user is on
> Deploy to production

- src/components/HowToUse/HowToUse.js
- src/components/SingleName/TransferRegistrars.js
> Minor issues

- src/routes/SingleName.js
> Fix error for tlds on Single Name

- src/components/SingleName/Name.js
> Show subdomains for tlds and subdomains

- src/api/registrar.js
This will fix https://github.com/ensdomains/ens-app/issues/228
> Check registrationDate against legacyEntry

- src/components/Forms/Button.js
- src/components/SingleName/DetailsItemEditable.js
- src/components/SingleName/NameDetails.js
- src/routes/Home.js
* Sync button and border radius on search box
* Sync on medium not small
* Add expiration date to auctioned names
* Fixed visited/hover bug homepage
* Abstracted legacy auction domain identifier into function
> Bug fixes deploy to production (#247)

- src/components/SingleName/NameDetails.js
- src/components/SingleName/TransferRegistrars.js
- Fix #253 
- Display registrant address
- Do not show migration modal if the user is not deedOwner
> Fix migration error

- src/components/SingleName/NameDetails.js
- src/components/SingleName/TransferRegistrars.js
* Add legacy registrant
* Only allow DeedOwner to transfer
> Fix migration error (#253)

- src/api/registrar.js
- src/components/SingleName/Name.js
> Fix 0x00000.eth

- src/components/SingleName/AddRecord.js
- src/components/SingleName/RecordsItem.js
- src/utils/records.js
Fix https://github.com/ensdomains/ens-app/issues/245
> Fix problem not showing warning on invalid address/content

- package.json
- yarn.lock
> Run prettier on commit

- src/utils/dates.js
Fixes https://github.com/ensdomains/ens-app/issues/285
> Display in 24 hr format

- src/components/SetupName/SetupName.js
- src/components/SingleName/NameDetails.js
Fixes https://github.com/ensdomains/ens-app/issues/243
> Open modal when resolver is not set

- src/components/SingleName/Name.js
Fixes https://github.com/ensdomains/ens-app/issues/231
> Rename owner into either Registrant or Controller

- src/api/registrar.js
- src/api/registry.js
- src/api/resolverUtils.js
This is to fix https://github.com/ensdomains/ens-app/issues/260
> Try/Catch estimateGas

- src/api/registrar/resolvers.js
- src/routes/SearchResults.js
- src/utils/utils.js
This will handle normal cases like 💩💩💩💩.eth correctly. The edge cases like  👩‍❤️‍👨 are not and should be handled in the separate PR once we figure out what to do.
> Emoji length

- src/components/SearchName/Search.js
- src/routes/Home.js
* Homepage style fixes
* Normalise search term
> Mobile fixes

- src/components/SingleName/Name.js
- src/routes/SingleName.js
> Add scroll to top on single name page

- package.json
- src/api/manager/resolvers.js
- src/components/SingleName/Name.js
- yarn.lock
> Unknown hash

- package.json
- yarn.lock
> Fix test registrar

- package.json
- yarn.lock
* Upgrade ensdomains/ui to fix provider/signer
* upgrade npm package
> Deploy Fix test registrar (#387)

- package.json
- src/App.js
- yarn.lock
Fix the compatibility of some lower cellphone systems.
Closed https://github.com/ensdomains/ens-app/issues/389
> fix: add object polyfill for some webview

- package.json
- src/components/SingleName/NameDetails.js
Deployed at https://bawdy-fork.surge.sh for testing
> Allow transfer for owner or parent domain owner

- package.json
- yarn.lock
To include the change at https://github.com/ensdomains/ui/pull/20 for myethevault support
> Add myethvault support

- package.json
- src/api/manager/resolvers.js
- src/components/DomainItem/DomainItem.js
- src/graphql/queries.js
- src/routes/Favourites.js
- yarn.lock
* Speed up loading favourites
* Remove unused queries
> Speed up favourites (#422)

- src/components/Forms/Button.js
- src/components/SingleName/Name.js
- src/components/SingleName/ShortName.js
- src/routes/Home.js
* Short name links
* Interim page
* Remove log
> Short name interim

- package.json
- src/api/manager/resolvers.js
- src/components/QueryAccount.js
- src/components/SingleName/Name.js
- src/graphql/fragments.js
- src/routes/SearchResults.js
- src/routes/SingleName.js
- yarn.lock
* Refactored Single Name to run more in parallel
* Updated @ensdomains/ui to run more in parallel
> Single name speed improvements and refactoring (#434)

- package.json
- src/components/SingleName/Name.js
- src/components/SingleName/ShortName.js
- src/routes/Home.js
- yarn.lock
* Change Short name page to link to OpenSea
> Short name links (#427)

- src/components/SingleName/ShortName.js
* Hit OpenSea before redirecting
* Hit OpenSea first to get the URL ready
> Hit OpenSea before redirecting (#465)

- package.json
- src/components/Links/ContentHashLink.js
- src/utils/records.js
- yarn.lock
Solves https://github.com/ensdomains/ens-app/issues/445
> Ipfs format

- public/manifest.json
Addressing https://github.com/ensdomains/ens-app/issues/339
> Change manifest name to ENS App

- src/components/Links/ContentHashLink.js
To fix https://github.com/ensdomains/ens-app/issues/379
> Do now allow wrap on whitespace

- .gitignore
- package.json
- src/api/manager/resolvers.js
- src/components/SingleName/AddRecord.js
- src/components/SingleName/NameDetails.js
- src/components/SingleName/RecordsItem.js
- src/components/SingleName/TextRecord/TextRecord.js
- src/components/SingleName/TextRecord/constants.js
- src/components/SingleName/TextRecord/index.js
- src/graphql/mutations.js
- src/graphql/queries.js
- src/utils/records.js
* add textRecord component
* Add workspace to gitignore
* Add resolvers and mutations for text record
* Basic textrecord support
* don't show text records if none are found
* Add Record functionality
* Move text record keys into constants file. Added dropdown for text record keys
* Style Input and fix delete
* Fix grid for mobile
* Fix edit box styles
* upgrade ui library
> Deploy to production - Text record (#483)

- package.json
- src/components/SingleName/Address/Address.js
- src/components/SingleName/Address/constants.js
- src/components/SingleName/KeyValueRecord/KeyValueRecord.js
- yarn.lock
- Depending on https://github.com/ensdomains/ui/pull/33
- Test deployed at http://sticky-shirt.surge.sh
> Address encoder 2

- .travis.yml
- src/components/SingleName/AddRecord.js
This is to address https://github.com/ensdomains/ens-app/issues/506
The below is the new styling to make dropdown button bigger on mobile.
> style dropdown for mobile width

- src/components/SingleName/NameRegister/NameRegister.js
- src/components/SingleName/ShortName.js
- src/routes/Home.js
- Pass label instead of name to getPrice
- Remove mention of OpenSea
- Show error message for 1-2 chars.
> Price UI bug fix + Remove the mention of opensea

- src/utils/analytics.js
To fix https://github.com/ensdomains/ens-app/issues/540
> Rename manager to app

- cypress/integration/registryMigration.spec.js
- package.json
- src/components/SingleName/Name.js
- src/components/SingleName/NameDetails.js
- yarn.lock
Addresses https://github.com/ensdomains/migration/issues/37
> Add tests on subdomain registry migration

- package.json
- src/api/manager/resolvers.js
- yarn.lock
> Deploy fix of default resolver

- package.json
Need to keep it disabled until root key holder meeting ends on 10th
> Disable registration

- src/components/SingleName/NameDetails.js
Addresses github issue #574 
it now allows registrant to transfer registrar address or set controller address
> Allow registrant to migrate without registry not being migrated

- cypress/integration/nameDetail.spec.js
- cypress/integration/resolverMigration.spec.js
- package.json
- src/api/manager/resolvers.js
- src/testing-utils/preTest.js
- yarn.lock
Add test case to test migration of old resolver with setContent.
> Fix failing tests

- public/index.html
- src/api/manager/resolvers.js
- src/components/ErrorModal/ErrorModal.js
- src/components/ErrorModal/index.js
- src/components/SingleName/ResolverAndRecords/ResolverMigration.js
> remove encoding of contenthash to allow migrating unknowns

- public/index.html
- src/api/manager/resolvers.js
- src/components/ErrorModal/ErrorModal.js
- src/components/ErrorModal/index.js
- src/components/SingleName/ResolverAndRecords/ResolverMigration.js
* remove encoding of contenthash to allow migrating unknowns
* Add basic error modal for resolver migration
> Deploy to production (#587)

- cypress/integration/resolverMigration.spec.js
- package.json
- src/api/ens.js
- src/api/manager/resolvers.js
- src/api/registrar/resolvers.js
- src/api/rootResolver.js
- src/api/subDomainRegistrar/resolvers.js
- src/components/DomainItem/ChildDomainItem.js
- src/components/SingleName/DetailsItemEditable.js
- src/components/SingleName/ResolverAndRecords/ResolverAndRecords.js
- src/components/SingleName/ResolverAndRecords/ResolverMigration.js
- src/index.js
- src/utils/utils.js
- yarn.lock
* Refactor frontend to use new classes
* Fix public resolver
* Fix resolver migration
* Fix testRegistrar
* Add new ui lib
* Update timeouts, remove hardcoded waits
> Update to new ENS class (#606)

- src/index.js
Fixing https://github.com/ensdomains/ens-app/issues/599
Should now show this message
> set client on error

- src/components/SingleName/DNSNameRegister/NameRegister.js
- src/components/SingleName/NameDetails.js
- src/components/SingleName/ResolverAndRecords/KeyValueRecord/KeyValueRecord.js
- src/components/SingleName/ResolverAndRecords/RecordsItem.js
> Fix mobile styling

- src/components/SingleName/ResolverAndRecords/KeyValueRecord/KeyValueRecord.js
Fix https://github.com/ensdomains/ens-app/issues/646 and https://github.com/ensdomains/ens-app/issues/647
> Fix text record bug

- src/components/IPFS/Login.js
- src/components/IPFS/Upload.js
- src/components/IPFS/config.js
This PR does the following
- Adds a link to where people can manage their uploaded pins
- Removes hard coded links and puts them in the config file so each provider can link to their own management tool
> Add manage pin link to upload component

- src/components/IPFS/Dropzone.js
- src/components/IPFS/Login.js
- src/components/SingleName/ResolverAndRecords/AddRecord.js
This pull request does 3 things
- Adds text after signing up for an account that tells the user "Check your email to verify your account" for the IPFS upload component.
- Changes the `new upload` button when adding a new record to better fit with the rest of theme. Instead of being greyed out by default it is now light blue like the other buttons.
- Changes the IPFS `Folder Upload` & `File Upload` buttons to use the same theme as the rest of the app instead of custom styling.
> Add verify email text

- src/components/SingleName/ResolverAndRecords/KeyValueRecord/KeyValueRecord.js
https://github.com/ensdomains/ens-app/issues/668
> Do not display other addresses if not exist

- src/components/Links/TextRecordLink.js
https://github.com/ensdomains/ens.domains/issues/102
> Display avatar URL

- src/components/NetworkInformation/NetworkInformation.js
Fixes #703
Fixes a crash in the app.  I don't fully grok how this code is supposed to work, just that as it does is currently broken and crashes the app for me.
No.  I'm hoping for CI to do that... if not then feel free to close this and let someone who cares more apply the fix.
- [❓] My code implements all the required features.
> Fixes crashing bug in AccountContainer.

- cypress/integration/reverse.spec.js
- src/api/manager/resolvers.js
fixes subgraph returning an error
> Fix Subgraph returning an error

- src/components/Links/TextRecordLink.js
To fix https://github.com/ensdomains/ens-app/issues/729
> Make linkContainer display as block to fix indentation issue

- src/components/DomainItem/ChildDomainItem.js
https://github.com/ensdomains/ens-app/issues/717
Shows grace period if already expired (address page have smaller than detail page so don't really have space to show both).
> Add grace period into address

- public/locales/en/translation.json
- src/components/DomainItem/ChildDomainItem.js
- src/components/SingleName/DetailsItemEditable.js
https://github.com/ensdomains/ens-app/issues/734
> Add warning on renewal if not registrant

- src/components/Basic/TopBar.js
- src/components/Loader.js
- src/components/SingleName/DetailsItem.js
- src/components/SingleName/NameDetails.js
- src/components/SingleName/ResolverAndRecords/KeyValueRecord/KeyValueRecord.js
- src/components/SingleName/ResolverAndRecords/RecordsItem.js
- src/components/SingleName/SaveCancel.js
- src/components/SingleName/Tabs.js
Fixed broken styling. Tightened up mobile styling
> Tighten up styling

- src/components/NetworkInformation/NetworkInformation.js
https://github.com/ensdomains/ens-app/issues/771
> no round avatar

- src/components/SearchErrors/SearchErrors.js
https://github.com/ensdomains/ens-app/issues/580
> Reword non supported TLD message

- .gitignore
- src/components/Address/RenewAll.js
Do not show `reminder` email notification link if the address does not own any names.
> No reminder

- .gitignore
- cypress/integration/address.spec.js
- cypress/integration/favorites.spec.js
- cypress/integration/search.spec.js
- src/api/registrar/resolvers.js
- src/components/DomainItem/ChildDomainItem.js
- src/components/DomainItem/DomainItem.js
- src/components/DomainItem/ExpiryDate.js
- src/graphql/queries.js
- src/routes/Favourites.js
- src/utils/dates.js
This change will show expiry date (or grace period if passed expiry date) in the following area
- Search page
- Address page
- Favorite page
> Show expiry date

- public/locales/cn.json
- public/locales/en.json
- public/locales/ja.json
Addressing https://github.com/ensdomains/ens-app/pull/593
> Lowercase EtherScan to Etherscan

- src/components/Address/RenewAll.js
- src/components/SingleName/DetailsItemEditable.js
- src/components/SingleName/NameRegister/NameRegister.js
- src/utils/dates.js
https://github.com/ensdomains/ens-app/issues/554
Tested the following three points
- Can register
- Can renew 
- Can bulk renew
> parseInt duration to prevent floating points

- cypress/integration/legacyRegistrarMigration.spec.js
- package.json
- src/components/SingleName/NameDetails.js
- src/components/SingleName/ReleaseDeed.js
- src/components/SingleName/TransferRegistrars.js
- yarn.lock
https://github.com/ensdomains/ens-app/issues/788
Owner
Non Owner
> Make Return button unclickable if not owner

- public/locales/cn.json
- public/locales/en.json
- public/locales/ja.json
- src/components/SingleName/NameRegister/NotAvailable.js
Fixed NotAvailable in SingleName Components to be multilingual.
#809
> fix Multilingualization of NotAvailable Components

- public/locales/de.json
Hey there,
thanks for accepting my German translation earlier and for the Twitter shout out! Happy to help! After having seen my translation on the live website I found some mistakes and ways to improve it, which I did in this PR.
As I already said via Twitter DM: Feel free to reach out whenever you change something on the website, happy to update the translation accordingly 🙌!
I updated the file "`public/locales/de.json`", nothing else.
* Updated the translation, wording and some wrong punctuations
* Tried it locally, all works. Should behave the same as my earlier PR since I only changed the locale-file.
> Improve German Translation

- src/components/DomainItem/ChildDomainItem.js
From https://github.com/ensdomains/ens-app/issues/797
To
> Fix subdomain sytling for asian chars

- cypress/integration/search.spec.js
- public/locales/cn.json
- public/locales/de.json
- public/locales/en.json
- public/locales/ja.json
* Update en.json
* Update cn.json
* Update de.json
* Update ja.json
* Update ja.json
* Update en.json
* Update de.json
* Update cn.json
* Fix broken test
Co-authored-by: Makoto Inoue <2630+makoto@users.noreply.github.com>
-
-
-
> Fix search title copy and some punctuation (#850)

- src/api/manager/resolvers.js
- src/components/PendingTx.js
- src/components/SingleName/NameRegister/CTA.js
- src/components/SingleName/NameRegister/NameRegister.js
- src/graphql/queries.js
To address https://github.com/ensdomains/ens-app/issues/866
> Add waitBlockTimestamp

- package.json
- src/api/registrar/resolvers.js
- src/components/NetworkInformation/useNetworkInfo.js
- src/components/SingleName/NameRegister/CTA.js
- src/components/SingleName/NameRegister/NameRegister.js
- src/components/SingleName/NameRegister/ProgressRecorder.js
- src/components/SingleName/NameRegister/ProgressStore.js
- src/graphql/mutations.js
- src/graphql/queries.js
- yarn.lock
- If user refresh page during step 1, it goes back to step 1 (I did not record step 1 as people could cancel or replace transaction with new one to up gas price).
- It records the current progress from step 2 once it receives the confirmation for the first transaction.
- If user leave the tab longer than 1 day, it will expire and the user has to start from step 1
> Persist progress

- src/components/SingleName/NameDetails.js
- src/components/SingleName/ReleaseDeed.js
- src/components/SingleName/TransferRegistrars.js
To fix https://github.com/ensdomains/ens-app/issues/882
> Allow deed owner to claim

- src/api/manager/resolvers.js
This problem happens when the registrant is set but not the controller
Fixes https://github.com/ensdomains/ens-app/issues/896
> Show owned if not available

- cypress/integration/legacyRegistrarMigration.spec.js
- public/locales/cn.json
- public/locales/de.json
- public/locales/en.json
- public/locales/ja.json
- src/components/SingleName/ReleaseDeed.js
Solves https://github.com/ensdomains/ens-app/issues/901
> link-reclaim

- src/components/SingleName/DetailsItemEditable.js
Resolves https://github.com/ensdomains/ens-app/issues/934
> Remove Trash bin from controller

- src/components/Links/ContentHashLink.js
Addressing https://github.com/ensdomains/ens-app/pull/936#pullrequestreview-504057884
> Replace dweb link

- package.json
- src/components/SingleName/NameRegister/CTA.js
- yarn.lock
Solves https://github.com/ensdomains/ens-app/issues/951
> Max commitment age

- public/locales/en.json
- src/components/SingleName/ResolverAndRecords/ContentHash.js
- src/components/SingleName/ResolverAndRecords/Records.js
> Fix learnmore

- public/locales/en.json
- src/components/SingleName/ResolverAndRecords/ContentHash.js
- src/components/SingleName/ResolverAndRecords/Records.js
* Update english translation for learnmore
* Fix 0x00 contenthash
* Change style to grey for contenthash
* Fix all 0x contenthashes
* Make 0x check generic to any length
-
-
-
> Deploy to live

- public/locales/en.json
- src/components/DomainItem/DomainItem.js
- src/routes/Favourites.js
Fixes https://github.com/ensdomains/ens-app/issues/974
> Combine favorite domain and subdomain

- cypress.json
- cypress/integration/nameDetail.spec.js
- cypress/integration/registryMigration.spec.js
- src/components/SingleName/ResolverAndRecords/Coins/Coins.js
- src/components/SingleName/ResolverAndRecords/KeyValueRecord/KeyValueRecord.js
- src/components/SingleName/ResolverAndRecords/Records.js
https://github.com/ensdomains/ens-app/issues/999
- Pass the result of GET_RESOLVER_FROM_SUBGRAPH to getAddresses
- If no addresses, return COIN_PLACEHOLDER_RECORDS
- Refactored cypress/integration/nameDetail.spec.js test to combine individual record addtion/modification into one.
> Do not pass entire COIN_LIST to getAddresses

- src/components/SingleName/NameDetails.js
- src/utils/records.js
Currently `Request to Register` button is clickable (but throws an error) even when it's in read only mode.
This fix correctly address that
> Add isEmptyAddress

- src/components/LanguageSwitcher/LanguageSwitcher.js
- src/components/SingleName/NameRegister/Price.js
> Show USD Oracle price

- src/routes/Faq.js
Fixes https://github.com/ensdomains/ens-app/issues/1016
> fix-faq-background

- public/locales/cn.json
- public/locales/de.json
- public/locales/en.json
- public/locales/es.json
- public/locales/fr.json
- public/locales/ja.json
- public/locales/ko.json
- public/locales/pl.json
- public/locales/ru.json
- public/locales/vi.json
- src/api/manager/resolvers.js
- src/components/SingleName/NameRegister/CTA.js
- src/components/SingleName/NameRegister/NameRegister.js
- src/graphql/queries.js
> Add Insufficient gas message on registration

- public/locales/cn.json
> update cn.json on 20210102

- src/components/Links/ContentHashLink.js
- src/components/SingleName/ResolverAndRecords/Certificate.js
- src/components/SingleName/ResolverAndRecords/ContentHash.js
- src/components/SingleName/ResolverAndRecords/Records.js
- src/components/SingleName/ResolverAndRecords/RecordsCheck.js
- src/components/SingleName/ResolverAndRecords/RecordsItem.js
- src/components/SingleName/ResolverAndRecords/RequestCertificate.js
* fix-faq-background
* Added requestCertificate
* Add header and cors policy
* Change to correct header
* Add .eth.domains to external link
* Change from .domains to .link
* Add requestCertificate
* Create certificate for a domain, not for subdomain
* Fix test error and also change it to request of subdomain if parent domain certificate does not exist
* Change endpoint from eth.domains to eth.link
> Deploy live: Request certificate (#1030)

- public/locales/cn.json
> update cn.json on 20210131

- src/components/Links/ContentHashLink.js
Fixes https://github.com/ensdomains/ens-app/issues/1114
> Change swarm endpoint

- cypress/integration/address.spec.js
- cypress/integration/favorites.spec.js
- cypress/integration/search.spec.js
- package.json
- public/locales/cn.json
- public/locales/de.json
- public/locales/en.json
- public/locales/es.json
- public/locales/fr.json
- public/locales/ja.json
- public/locales/ko.json
- public/locales/pl.json
- public/locales/ru.json
- public/locales/vi.json
- src/components/Address/Address.js
- src/components/Address/DomainList.js
- src/components/Address/Pager.js
- src/components/Address/RenewAll.js
- src/components/DomainItem/ChildDomainItem.js
- src/components/DomainItem/DomainItem.js
- src/components/Forms/Select.js
- src/components/Icons/ActiveHeart.js
- src/components/Icons/InActiveHeart.js
- src/routes/Favourites.js
- src/utils/graphql.js
- yarn.lock
- Add pagination on /address
- Allow users to add names to favourite from /address page
- Allow users to renew from favourite page
- Add warning if users try to renew names which are not owned by the connected address.
- Fixed error on gas estimation error
> Multi renewal

- src/routes/Faq.js
* Corrected spelling of "relatively"
> Small typo

- README.md
- public/locales/it.json
- src/components/LanguageSwitcher/LanguageSwitcher.js
- src/i18n.js
- yarn.lock
> Italian translation added

- src/graphql/queries.js
- src/routes/Favourites.js
Fix https://github.com/ensdomains/ens-app/issues/1135
Before
After
The problem happens when merging the favourites list and its registration list as it was assuming that the registration list gets to return in the same order as the favourite list.
> Fix sorting issue on favourite

- src/components/Links/RecordLink.js
- src/components/SingleName/ResolverAndRecords/Records.js
- src/constants/textRecords.json
Issue #
https://github.com/ensdomains/ens-app/issues/1140
Hey, so I changed two files, textRecords.json as that was the first place I thought to look. That wasn't changing anything, then I found Records.js which was using a new array of placeholder text records. I changed those as well and the website was updated as you can see in the screencap
- Code is now migrated from legacy keys
I saw the changes reflected ( localhost/name/foo.eth/details )
Previous keys:
Imported keys:
I imported the json file as the const in Records.js was mostly redeclaring everything. Just to make it easier to make changes in future. Hope this helps :)
> Vendor prefix change

- package.json
- src/api/web3modal.js
- yarn.lock
> Including coinbase wallet in web3modal 

- src/components/Calendar/Dropdown.js
- src/components/ExpiryNotification/ExpiryNotifyDropdown.js
- src/components/LanguageSwitcher/LanguageSwitcher.js
- src/components/hooks.js
Resolves #1161 
Same issue was in language drop down as well, both resolved.
> Cancel dropdown when click outside

- src/components/AddReverseRecord.js
- src/graphql/queries.js
> Check if domain has ETH record available in reverse record registry

- package.json
- yarn.lock
Wallet connect team have released a fix for recent issues
> bump wallet connect version

- cypress/integration/nameDetail.spec.js
- package.json
- src/components/Links/RecordLink.js
- src/components/SingleName/ResolverAndRecords/KeyValueRecord/KeyValueRecord.js
- src/components/SingleName/ResolverAndRecords/ResolverMigration.js
- yarn.lock
Now passing required prop to ViewOnly, added cypress test to check viewonly record is visible
> Viewonly fix

- src/components/Links/RecordLink.js
- src/components/NetworkInformation/NetworkInformation.js
- src/components/SingleName/ResolverAndRecords/KeyValueRecord/KeyValueRecord.js
- src/components/SingleName/ResolverAndRecords/Records.js
- src/utils/utils.js
- Implemented nft section of this draft avatar format https://gist.github.com/Arachnid/9db60bd75277969ee1689c8742b75182
- Show nft avatar on top left avatar page and right side text record
- Only for rinkeby (for now)
- Test deployed at https://nftavatarrinkeby.surge.sh/name/matoken.eth
> Show avatar on Rinkeby

- cypress/integration/address.spec.js
- src/components/Address/Address.js
- src/components/SearchName/Search.js
- src/routes/Favourites.js
- src/routes/SearchResults.js
- src/routes/SingleName.js
- src/utils/utils.js
Fixing https://github.com/ensdomains/ens-app/issues/1233
> Filter unnormalised

- public/locales/cn.json
Updated the Chinese translation of the app, especially an important ATTENTION before registering.
> updata cn.json on 20210720

- src/components/Links/RecordLink.js
- src/components/hooks.js
- show "Owner" label if the NFT  is owned by the address of the ENS name 
- Link to OpenSea URL
> Show ownership of the avatar

- .travis.yml
- src/components/Links/RecordLink.js
- src/components/hooks.js
- src/utils/utils.js
Updating avatar endpoint response parameters, based on json type changes here and network parameter addition in here.
> update useAvatar params

- src/components/Banner/DAOBanner.js
- src/components/hooks.js
We are still increasing by 10% to prevent Oracle price change which all registered users get back the diff once registration is complete.
Also tweaked the banner page to make the link area bigger
> Change price estimate from 150% to 110%

- src/components/IPFS/config.js
fix typo in IPFS/config.js
- fix typo
no need test
> fix typo in config.js

- .gitpod.yml
Gitpod helps contributors to fire a new workspace all setup
- Contribute from iPad
- Don't need local setup
- Saves local system space
- Easy to share demo with others
- Signup to Gitpod
- Open https://gitpod.io/#https://github.com/bigint/ens-app/tree/bigint/gp-support
> feat: add gitpod support

- src/components/SideNav/SideNav.js
Remove unused isENSReady import
> chore: remove unused isENSReady import

- src/routes/Faq.js
Fix typo in src/routes/FAQ.js
- fixed a typo
Not necessary, since it's only a text change
> Fix typo in FAQ

- src/components/AddReverseRecord.js
> Don't return function call from useEffect

- public/locales/pt-BR.json
- src/components/LanguageSwitcher/LanguageSwitcher.js
- src/i18n.js
Hello, in this week i had my first contact with ENS. So i figure out that the web site hasn't a Portuguese-BR translation, then i made one based on the last `en.json` structure. 
Ran the app locally and verified that the language switch works. Don't believe there should be any side-effects for this PR.
> feature: pt-BR translation

- cypress/integration/reverse.spec.js
- src/apollo/typePolicies.js
to make the displayName more readable just like metamask`s short address
> make the displayName more readable

- src/App.js
- src/App.spec.js
- src/apollo/reactiveVars.js
- src/apollo/typePolicies.js
- src/components/Address/Address.js
- src/components/Address/Pager.js
- src/components/Error/Errors.js
- src/graphql/queries.js
- src/routes/Favourites.js
- src/setup.js
- src/utils/utils.js
#1370
If an account has one or more domain names containing UTS46 forbidden characters (e.g. "???.eth"), the ens app goes blank. See example from issue:
https://app.ens.domains/address/0xC66135b1671aD1f2cAE217ff19234A77F7A0B00c
This PR catches the error and renders an error page inviting the user to go back to the home page.   
- Update initial value `globalErrorReactive` variable
- Update `globalError` field on `Query` type in cache policy
- Abstract `GET_ERRORS` query to the queries file
- Update argument `globalErrorReactive` variable
- Subscribe to the value of `globalErrorReactive` in `Address` and `Favourites` components 
- Catch error invalid characters in `filterNormalised` method and update `globalErrorReactive` variable
- Reset `globalErrorReactive` variable when user goes back …
> Error page invalid characters

- src/components/NetworkInformation/NetworkInformation.js
> fix the accout container cover the main content

- src/api/delegate.js
- src/apollo/mutations/mutations.js
- src/hooks/useReactiveVarListeners.js
- src/routes/Faq.js
- src/setup.js
fixed issue with no connection
> Add delegate popup - hotfix

- src/components/Address/Address.js
- src/components/Address/DomainList.js
- src/components/DomainItem/ChildDomainItem.js
- src/components/DomainItem/DomainItem.js
- src/routes/Favourites.js
- src/utils/utils.js
- src/utils/utils.spec.js
#1346 
The app will now show invalid names on the address and favourites page but with a warning message
Added unit tests for the function that detects unnormalised names 
Manually checked with this address: http://localhost:3000/address/0x147ca0da3a1ecef2c1892d518266c9f3279bb8bc/registrant?page=1
Also favourites some of these addresses and checked the favourites page
> Handle non-normalised names better

- public/locales/de.json
- public/locales/en.json
- public/locales/es.json
- public/locales/fr.json
- public/locales/ja.json
- public/locales/ko.json
- public/locales/pl.json
- public/locales/ru.json
- public/locales/vi.json
- src/components/SingleName/NameRegister/LineGraph.js
- src/components/SingleName/NameRegister/NameRegister.js
https://github.com/ensdomains/ens-app/issues/1431
Fix displaying wrong chart when the price premium changed from 2000 to 100000
- change the starting price from 2000 to 100000
- small refactor to reuse the variable
- update translation
Manual test
> Change premium price from 2000 to 100000

- public/locales/de.json
- public/locales/en.json
- public/locales/es.json
- public/locales/fr.json
- public/locales/ja.json
- public/locales/ko.json
- public/locales/pl.json
- public/locales/ru.json
- public/locales/vi.json
- src/components/SingleName/NameRegister/LineGraph.js
- src/components/SingleName/NameRegister/NameRegister.js
> Change premium price from 2000 to 100000 (#1433)

- docs/gnosis_safe_app_support.md
Fixed typo.
```
withing -> within
```
-
-
-
> Fix typo in gnosis_safe_app_support.md

- src/components/Banner/DAOBanner.js
Make the eligibility date more explicit
> Change banner

- src/components/SingleName/DetailsItemEditable.js
- src/components/SingleName/NameRegister/Price.js
- src/components/SingleName/NameRegister/PriceCalculator.js
Address https://github.com/ensdomains/ens-app/issues/1452
- Show ETH price with 3 decimal instead of 2
- Set default premiumOnlyPrice to 0 (renewal as no premium)
- Fix GET_ETH_PRICE on DetailtemEditable
> Fix GET_ETH_PRICE and toFixed to 3

- package.json
- src/components/SingleName/NameRegister/Price.js
- src/components/SingleName/NameRegister/PriceCalculator.js
- yarn.lock
This is to fix https://github.com/ensdomains/ens-app/issues/1451 
The problem happens when testnet doesn't have chainlink oracle contract set to `eth-usd.data.eth`
Dependency https://github.com/ensdomains/ui/pull/157
> Fix an error of not showing registration page on testnets

- scripts/serve.js
- src/api/web3modal.js
This is fix to make MEWconnect connection work!
> fix: mewconnect

- .travis.yml
- README.md
- cypress/integration/subgraph.spec.js
- package.json
- scripts/graph-node.js
> fix graph e2e tests

- src/utils/utils.js
This fixes the error of not showing address list from /
> catch erron on hash(domain?.name)

- package.json
- src/components/SingleName/NameRegister/Price.js
- src/components/SingleName/NameRegister/PriceCalculator.js
- yarn.lock
- Do not show "undefined" when price oracle ens is not set
- Change oracle text record from `ens.eth` to `.eth` https://github.com/ensdomains/ui/pull/162
Run the following query on https://thegraph.com/hosted-service/subgraph/ensdomains/ensropsten
```
{
registrations(first:5, where:{expiryDate_gt:"1641035869"}, orderBy:expiryDate){
expiryDate
labelName
}
}```
> A few changes to make sure new exponential pricing works on Ropsten

- src/components/SingleName/NameRegister/NameRegister.js
- sets apollo fetch policy for rent price query in NameRegister component
> fix price being cached

- cypress/integration/nameDetail.spec.js
- cypress/integration/search.spec.js
- src/components/SearchName/Search.js
- src/routes/SingleName.js
> added redirect for nameDetails and encodeURI for search bar

- package.json
- yarn.lock
Bumps ens-avatar library version from 0.1.4 to 0.1.5
> ens-avatar lib version bump 0.1.5

- src/setup.js
This fixes the issue where MEWWallet exits after connecting
> Only call .removeAllListeners if it exists

- .gitignore
- .travis.yml
- README.md
- docker-compose.yml
- scripts/graph-setup.sh
Moves the docker-compose file and setup script previously used from the [graph-node](https://github.com/graphprotocol/graph-node/blob/master/docker/docker-compose.yml) repo, and changes the travis deploy file to use said files.
> Fix test speed

- package.json
- src/api/web3modal.js
- src/apollo/mutations/ens.js
- src/rpcUrl.js
- src/setup.js
- yarn.lock
Removes infura and replaces with cloudflare eth
> Remove infura

- package.json
- yarn.lock
> hotfix for connection

- cypress.json
- cypress/integration/nameDetail.spec.js
- cypress/support/commands.js
- package.json
- src/api/avatar.js
- src/api/avatar.test.js
avatar func was using getNetworkProviderUrl which is now removed from UI, switched to getProvider.
> Avatar field fix

- package.json
- src/api/web3modal.js
- src/apollo/mutations/mutations.js
- src/setup.js
- src/setup.spec.js
- yarn.lock
This change should allow to query ccip-read/wildcard based resolver under wallet connect provider.
To test, please connect via wallet connect and go to /name/1.offchainexample.eth
**[Reference](https://github.com/WalletConnect/walletconnect-monorepo/issues/1000)**
> Use ethereum-provider

- public/locales/en.json
- src/components/Banner/DAOBanner.js
https://user-images.githubusercontent.com/1221141/192450165-2677ecc1-b2f3-449f-bc0f-eb346ad4ccd0.mov
> Add swag banner to replace constitution book

- public/locales/en.json
- src/components/Banner/DAOBanner.js
> Remove swag banner

- src/routes/Faq.js
- src/utils/dates.js
> fix typo and premium period variable for 21 day exponential period

- src/utils/utils.js
for raw arweave url usage, update supported avatar protocols list
> update supported avatar protocols list

- package.json
- src/utils/utils.js
- yarn.lock
this will bring arweave support to ens-app
> bump ens-avatar to 0.2.0 (#1578)

- src/utils/utils.js
fixes problem at:
https://app.ens.domains/address/0x2808b43f33022f20962d28849d430A3C935E851c
> fix: remove global illegal char error if not needed

- public/locales/cn.json
Updated the recently added text.
> update cn.json on 10/1/2022

- public/index.html
This is to add an aggregated view across different sites https://plausible.io/docs/plausible-script#is-there-a-roll-up-view
> add rollup.ens

- package.json
- src/utils/analytics.js
- yarn.lock
Add GA v4 support (should work along side with v3)
> Add react-ga4

- src/components/Address/Address.js
- src/components/SingleName/Name.js
- src/routes/Faq.js
- src/routes/Favourites.js
- src/routes/Home.js
- src/routes/SearchResults.js
> Remove constitution banner

- src/components/SingleName/NameRegister/EthRegistrationGasPrice.js
based on this dune query: https://dune.com/queries/2391303
avg is 260k
> fix: update registration gas estimate to be more accurate

- src/components/SingleName/NameRegister/ProgressRecorder.js
This adds https://docs.ens.domains/ens-improvement-proposals/ensip-14-platform-source-parameter.
00000002 is for v2 and 00000003 is for v3
> Add platformSource and version

- public/locales/es.json
> Updated Spanish (ES) localization to match (EN)
